version: '3'
services:
    db:
        build: ./
        restart: always
        ports:
            - 5432:5432
        volumes:
            - ./volumes/pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_HOST: 127.0.0.1
            POSTGRES_DB: company-management
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345
            POSTGRES_PORT: 5432
            POSTGRES_PORT_EXT: 5432
            API_GATEWAY_PORT_EXT: 3000
        container_name: db
